modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="project_coast"
version="${file.jarVersion}"
displayName="Project Coast"
logoFile="logo.png"
credits="DoltHHaven, Carmen"
authors="Team Taiga Modding"
description='''
Enhances beaches and things that are not beaches
'''

[[dependencies.project_coast]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.project_coast]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.project_coast]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[5.3.0,)"
    ordering = "BEFORE"
    side = "BOTH"